In [1]:
import pandas as pd
from keras.preprocessing.text import Tokenizer
from tools import load_data
from gensim.models import KeyedVectors
import numpy as np

/Users/oliver/miniconda3/envs/tensorflow/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [3]:
data = pd.read_csv("../data/train_bettle/relation.txt",sep='\t',header=None,names=["question","response","answer","label"])

In [19]:
text_uniq = [str(item) for item in data['value']]
tk = Tokenizer()
tk.fit_on_texts(text_uniq)

In [20]:
text_uniq[0]

'terminal 1 positive terminal separated gap'

In [21]:
tk.texts_to_sequences([text_uniq[0]])

[[4, 19, 10, 4, 38, 6]]

In [27]:
worddict = tk.word_index
type(worddict)

dict

In [28]:
tk2 = Tokenizer()
tk2.word_index = worddict

In [6]:
#tk2.texts_to_sequences([text_uniq[0]])
data['answer']

0       answer204 answer205 answer206 answer207 answer...
1       answer204 answer205 answer206 answer207 answer...
2       answer204 answer205 answer206 answer207 answer...
3       answer204 answer205 answer206 answer207 answer...
4       answer204 answer205 answer206 answer207 answer...
5       answer204 answer205 answer206 answer207 answer...
6       answer204 answer205 answer206 answer207 answer...
7       answer204 answer205 answer206 answer207 answer...
8       answer204 answer205 answer206 answer207 answer...
9       answer204 answer205 answer206 answer207 answer...
10      answer204 answer205 answer206 answer207 answer...
11      answer204 answer205 answer206 answer207 answer...
12      answer204 answer205 answer206 answer207 answer...
13      answer204 answer205 answer206 answer207 answer...
14      answer204 answer205 answer206 answer207 answer...
15      answer204 answer205 answer206 answer207 answer...
16      answer204 answer205 answer206 answer207 answer...
17      answer

In [2]:
x_train,y_train,x_test,y_test,dictionary_inv = load_data("../data/train_bettle/index_simple_token.txt","../data/train_bettle/relation.txt","../data/test_bettle/ua_index_query.txt","../data/test_bettle/ua_relation.txt","../data/word.txt",labeltype="5way")

In [3]:
relation_data = pd.read_csv("../data/test_bettle/ua_relation.txt",sep='\t',header=None,names=["question","response","answer","label"])

In [3]:
x_test

array([[array([ 4,  5, 15,  1, 12,  7,  8, 21,  9, 16,  1,  2,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0], dtype=int32),
        array([ 1,  2,  3,  4,  5, 15,  1,  6, 17, 18, 19,  2,  3,  4,  5,  1,  6,
       10,  2,  3,  4,  5,  1,  6,  7,  8,  4,  2, 12, 10,  7, 16,  4, 14,
       15,  2, 12, 11, 13,  4, 14, 15,  1,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
      dtype=int32)],
       [array([ 1, 26, 39,  5,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0], dtype=int32),
        array([ 1,  2,  3,  4,  5, 15,  1,  6, 17, 18, 19,  2,  3,  4,  5,  1,  6,
       10,  2,  3,  4,  5,  1,  6,  7,  8,  4,  2, 12, 10,  7, 16,  4, 14,
       15,  2, 12, 11, 13,  4, 14, 15,  1,  0,  0,  0,  

In [6]:
labledict=dict({"correct":0,"contradictory":1,"irrelevant":2,"non_domain":3,"partially_correct_incomplete":4})
y_lable = list(relation_data['label'])
y_lable = [labledict[label] for label in y_lable]

In [8]:
word2vecweight = KeyedVectors.load_word2vec_format("/Users/oliver/workplace/deeplearning/resource/eng.vectors.bin",binary=True)

In [15]:
words = word2vecweight.wv.vocab

/Users/oliver/miniconda3/envs/tensorflow/lib/python3.6/site-packages/ipykernel/__main__.py:1: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  if __name__ == '__main__':


In [16]:
labledict=dict({"correct":0,"contradictory":1,"irrelevant":2,"non_domain":3,"partially_correct_incomplete":4})

In [17]:
word_data = pd.read_csv("../data/word.txt",sep='\t',header=None,names=["word","index"])
word_dict = {}
word_dict_inverse = {}
for index,row in word_data.iterrows():
    word_dict[row["word"]] = row["index"]
    word_dict_inverse[row["index"]] = row["word"]

In [19]:
count =0
for key,_ in word_dict.items():
    if key in words:
        count += 1

In [26]:
word2vecweight["PAD"] = np.random.randn(200,)

TypeError: 'Word2VecKeyedVectors' object does not support item assignment

In [24]:
word2vecweight.get_keras_embedding()

(200,)

In [28]:
"am" in word2vecweight.wv.vocab

/Users/oliver/miniconda3/envs/tensorflow/lib/python3.6/site-packages/ipykernel/__main__.py:1: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  if __name__ == '__main__':


True

In [45]:
a = [[1,2]]
b = [2,3]
c = [4,5]
a.append(b)
a.append(c)
np.array(a).shape

(3, 2)

In [46]:
atest = x_test[:,0]


In [49]:
atest.reshape(atest.shape[0],-1)[0]

array([array([ 43, 100,  66, 103,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0], dtype=int32)], dtype=object)

In [70]:
qus = np.zeros((x_test[:,0].shape[0],x_test[:,0][0].shape[0],))
for i in range(x_test[:,0].shape[0]):
    qus[i] = x_test[:,0][i]

(439, 30)

In [73]:
qus[3]

array([ 43., 100.,  66., 103.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.])

In [89]:
x_train[:,0][:100]

array([array([ 43, 100,  66, 103,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0], dtype=int32),
       array([ 43, 100,  66, 103,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0], dtype=int32),
       array([ 43, 100,  66, 103,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0], dtype=int32),
       array([ 43, 100,  66, 103,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0], dtype=int32),
       array([ 43, 100,  66, 103,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0], dtype=int32),
       array([ 43, 100,  66, 103,  

In [90]:
relation_data = pd.read_csv("../data/train_bettle/relation.txt",sep='\t',header=None,names=["question","response","answer","label"])

In [92]:
refer = []
ans = []
for index,row in relation_data.iterrows():
    ans.append(row['response'])
    refer_str = ""
    for item in row['answer'].split(' '):
        #print(item)
        #for item in ansstr.split(' '):
        #    print(item)
        if item in query_dict:
            refer_str += query_dict[item]
    refer.append(refer_str)

NameError: name 'query_dict' is not defined